### ISSUE TITLE
Prototype: sprite: Question Box

### ISSUE THREAD

**Issue by drnikki** [drnikki/text-ile#24]
**Is your feature request related to a problem? Please describe.**
We need a function that will print this question box! (aka, the [mario coin box](https://www.google.com/search?q=mario+coin+question&client=firefox-b-1-d&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjS6v2U8rv-AhVRVTUKHRtVBaEQ0pQJegQIBBAC&biw=1482&bih=838&dpr=1.82) )

<img width="409" alt="image" src="https://user-images.githubusercontent.com/254939/233735628-da448e62-6e96-48ba-b9a6-e0cdbab867e8.png">

**Describe the solution you'd like**
A function that will print this box.  This box is not full-width, and so in the future, we *may* need to print it next to something else, so try to keep that in mind.  For this prototype, it simply needs to print.

**Comment by michaeljscrockett26** [comment]
Looks good!
