### ISSUE TITLE
Browser visualization: custom patterns on each receipt

### ISSUE THREAD

**Issue by drnikki** [drnikki/text-ile#32]
**Is your feature request related to a problem? Please describe.**
Not quite a problem, but - when you go to the multi-column visualization (called `column.html` as of #30), all of the receipts have the same contents.  

**Describe the solution you'd like**
What we need instead is for each of them to contain the approximate set of patterns that will be in the physical object. 

**Additional context**
The contents of each receipt will be described by @mollyinkilos in a comment below. 

**Testing for success**
Load the branch and look at each receipt - does it match roughly what molly is describing?

**Comment by mollyinkilos** [comment]
![image](https://user-images.githubusercontent.com/51466500/235006697-5aea4598-91e8-4b87-b378-e7a88e60c74c.png)

There will be two 7 column banner arrangements, one it the mirror image of the other:

Set 1
Column 1: Twinkle Banner & Starbursts. Twinkle Banners should be anchored at left
Column 2: Chandeliers
Column 3: Clouds and Question Boxes
Column 4: Triangle 1, Triangle 2, Bug
Column 5: Clouds and Question Boxes
Column 6: Chandeliers
Column 7: Rope

Set 2
Column 1: Rope
Column 2 Chandeliers
Column 3: Clouds and Question Boxes
Column 4: Triangle 1, Triangle 2, Bug
Column 5: Clouds and Question Boxes
Column 6: Chandeliers
Column 7: Twinkle Banner and Starburst, Twinkle Banner should be anchored right

**Comment by drnikki** [comment]
@Mango-Wei Can you start working on this visualization when you're next in the repo please? I saw that some of the things you were planning to work on got scooped by Michael. :)

**Comment by Mango-Wei** [comment]
Hi!
Sure!!!
 I'd love to and thanks for that. ;)


Dr. Nikki Stevens ***@***.***>于2023年5月1日 周一07:49写道：

**Comment by drnikki** [comment]
In order for this to be complete, #40 will need to be done.

**Comment by drnikki** [comment]
@Mango-Wei Hi!  Will you have a PR for this open before our meeting tomorrow? (If not, that's okay, please just push whatever you have to origin!)

**Comment by Mango-Wei** [comment]
Hi!!!!!!!
Currently I am working on the Question Mark and it should be finished
tonight, can I meet you tmr before our meeting about this?

Dr. Nikki Stevens ***@***.***> 于2023年5月4日周四 18:54写道：

**Comment by drnikki** [comment]
@Mango-Wei The question mark is done - all of the shapes on the visualization are done. :) They just need to be pulled in to each column.  But! we can absolutely meet before our meeting - I'll be in the space starting at 12ish.

**Comment by Mango-Wei** [comment]
OH my god, this is sooo quick!!    I see why I didn't find it because it is
named as "mario coin box" at github, I thought it should be a "question
box" or "question mark", I am sorry I didn't find that!!!!
Yes I will meet you at 12. Thanks for reaching out!


Dr. Nikki Stevens ***@***.***> 于2023年5月4日周四 19:04写道：
