### ISSUE TITLE
Separate Sprites into Separate Files

### ISSUE THREAD

**Issue by michaeljscrockett26** [drnikki/text-ile#33]
**Is your feature request related to a problem? Please describe.**
chandelier.js is starting to get very crowded, and using imports will hopefully help manage merge conflicts.

**Describe the solution you'd like**
Separate each sprite or related sprites into their own files. Export the print function from each file. A main.js or receipt.js file will import those functions to generate the receipt.

**Testing for success**
The code for building up the receipt is in a file separate from sprites, and the browser still generates a receipt as before.

**Comment by michaeljscrockett26** [comment]
Code is done. I want to wait for PR until we meet in person and to rebase after pending PRs.

**Comment by drnikki** [comment]
This is a good improvement.  @LeoBueno15 @Mango-Wei @michaeljscrockett26 do you think the three of you can coordinate getting this merged before our meeting on Friday?
