### ISSUE TITLE
FEEDBACK REQUEST: Open Source

### ISSUE THREAD

**Issue by drnikki** [drnikki/text-ile#43]
We're making -great- progress on this whole project and that means we'll have time to do one of my favorite things: convert a repository to open source (aka, make it all public and usable by someone else).

In this issue, I'd like to hear from you about what you think this repo needs before it can be made public and make sense to anyone else. 

So, just leave your thoughts in comments and we'll start breaking them into new issues!

**Comment by drnikki** [comment]
@Mango-Wei @LeoBueno15 @michaeljscrockett26 Hi all - just a reminder to drop some ideas about open sourcing the repo here.

**Comment by michaeljscrockett26** [comment]
- add doc comments absolutely everywhere
- add docs to github wiki 
     - i've never played around with github wiki before. I feel like it could be interesting
