### ISSUE TITLE
FEEDBACK REQUEST: Data

### ISSUE THREAD

**Issue by drnikki** [drnikki/text-ile#50]
I'd love to hear initial thoughts / ideas / wishes on ways to make relationships between what we're doing and the data that we have.  

An early version literally printed one character for each type of data that we have.  It looked like this
```
var commitSymbol = "~x~"; // 30,000  commits  to the repository
var userSymbol = "~/\\~"; // 18408  registered users
var nodeSymbol = "\\x\\"; // 18435  pieces of content (aka nodes) created
var commentSymbol = "\\{}/"; // 11250 comments
var taxonomySymbol = "/^/"; // 63555 taxonomy terms
var geditSymbol = "><"; // 4000 google document edits
```

**Comment by drnikki** [comment]
@Mango-Wei @LeoBueno15 @michaeljscrockett26 Hi all - just a reminder to drop some thoughts here before our meeting on Friday.

**Comment by michaeljscrockett26** [comment]
One simple thing could be to have each sprite correspond to a certain type of data. For example, every 50-100 comments is one cloud sprite.
