### ISSUE TITLE
Prototype: Starburst

### ISSUE THREAD

**Issue by drnikki** [drnikki/text-ile#6]
**Describe the solution you'd like**
Create Starburst according to [spec](https://docs.google.com/document/d/1i9bpHKvHs5wODJ3i2JuNVyC8qWN62NqCDI5p_wUlunI/edit) document.

The Starburst has a central character and a randomized spread of characters emanating from it.

**Testing for success**
- Visit browser demo
- See a variety of starbursts, randomized according to the spec document.

**Comment by LeoBueno15** [comment]
Yes! It is just about done, will make pr tonight.
