### ISSUE TITLE
Diamond Butterfly

### ISSUE THREAD

**Issue by LeoBueno15** [drnikki/text-ile#61]
**Is your feature request related to a problem? Please describe.**
Add diamond/butterly.

**Describe the solution you'd like**
Print two diamonds next to each other to form a butterfly. The image can vary in size at random. The diamonds are also filled with random "right" and "left" characters that can be: "{}", "()", "/\", "x".

**Additional context**
<img width="422" alt="Screen Shot 2023-05-13 at 10 03 26 AM" src="https://github.com/drnikki/text-ile/assets/81589600/71d424e9-862c-475b-b970-ed36c8179a42">

**Testing for success**
How will the pull request reviewer know that this solution is successful?

**Comment by drnikki** [comment]
Hi @LeoBueno15 is this almost done or can we have an open PR for Friday?

**Comment by LeoBueno15** [comment]
yes! I will make the pr for it
