### ISSUE TITLE
Prototype: Rope

### ISSUE THREAD

**Issue by drnikki** [drnikki/text-ile#8]
**Is your feature request related to a problem? Please describe.**
We need a receipt-wide rope!

**Describe the solution you'd like**
Build this rope according to [the spec](https://docs.google.com/document/d/1i9bpHKvHs5wODJ3i2JuNVyC8qWN62NqCDI5p_wUlunI/edit) document, which has the pictures of everything in it. 

**Testing for success**
Visit the in-browser demo, and see a column filled with randomized rope.

**Comment by michaeljscrockett26** [comment]
For sure! Just working out a few kinks.
