### ISSUE TITLE
Add a Contributors file

### ISSUE THREAD

**Issue by michaeljscrockett** [drnikki/text-ile#88]
We've all worked hard on this project. Let's add a Contributors file to the root directory to recognize our work.

**Comment by michaeljscrockett** [comment]
Should we and how do we recognize the artist team in this repo?

**Comment by drnikki** [comment]
Great question!  

I think we can list people by name, and those that have github handles can list those, but this way we can also recognize the artists, weavers, sprite designers, etc.

**Comment by mollyinkilos** [comment]
Good question Michael and good idea, Nikki.

**Comment by drnikki** [comment]
Satisfied this with the all-contributors bot.
